global with sharing class SettingHistoricsLetter {
  /*  
    public String eipSendEmail;
    public String eipCcSendEmail;
    public String eipAccount;
    public String eipContact;
    public String eipContractNumber;
    public String eipCustId;
    public String eipTypeNote;
    public String eipFileName;
    public String eipFile;
    public String eipContentType;
    public String eipLangue;
    public Date eipExpiryDate;
    public String sfdcCaseId;
    public String eipActiveDirectoryName;
    public String eipTypeLetter;
    public String eipDMSId;
    
    
     public SettingHistoricsLetter( String eipSendEmail, String eipCcSendEmail, String eipAccount, String eipContact, String eipContractNumber, String eipCustId,String eipTypeNote, 
                                  String eipFileName, String eipFile, String eipContentType, String eipLangue,Date eipExpiryDate, String sfdcCaseId, String eipActiveDirectoryName, 
                                  String eipTypeLetter, String eipDMSId){ 
                                      
                this.eipSendEmail = eipSendEmail;
                this.eipCcSendEmail = eipCcSendEmail;
                this.eipAccount = eipAccount;
                this.eipContact = eipContact;
                this.eipContractNumber = eipContractNumber;
                this.eipCustId = eipCustId;
                this.eipTypeNote = eipTypeNote;
                this.eipFileName = eipFileName;
                this.eipFile = eipFile;
                this.eipContentType = eipContentType;
                this.eipLangue = eipLangue;
                this.eipExpiryDate = eipExpiryDate;
                this.sfdcCaseId = sfdcCaseId;
                this.eipActiveDirectoryName = eipActiveDirectoryName;
                                      
              	this.eipTypeLetter = eipTypeLetter;
                this.eipDMSId = eipDMSId;
                                    }
*/
}