global with sharing class SettingHistoricsBuyout {
 /*   
    public String eipSendEmail;
    public String eipCcSendEmail;
    public String eipAccount;
    public String eipContact;
    public String eipContractNumber;
    public String eipCustId;
    public String eipTypeNote;
    public Decimal eipAmount;
    public Decimal eipEndOfTermFee;
    public Decimal eipTaxesGST;
    public Decimal eipTaxesPST;
    public Decimal eipTaxesHST;
    public Decimal eipTotalBuyout;
    public String eipBuyoutType;
    public String eipFileName;
    public Date eipBuyoutDate;
    public String eipFile;
    public String eipContentType;
    public String eipOperationType; 
    public String eipLangue;
    public List<String> eipDescripition;
    public Integer eipBuyoutTerm;
    public Decimal eipRate;
    public Date eipExpiryDate;
    public String sfdcCaseId;
    public Decimal eipBalanceAmount;
    public String eipActiveDirectoryName;
    
  
        
        public SettingHistoricsBuyout( String eipSendEmail, String eipCcSendEmail, String eipAccount, String eipContact, String eipContractNumber, String eipCustId,
                                    String eipTypeNote, Decimal eipAmount, Decimal eipEndOfTermFee, Decimal eipTaxesGST, Decimal eipTaxesPST, Decimal eipTaxesHST, 
                                    Decimal eipTotalBuyout, String eipBuyoutType, String eipFileName, Date eipBuyoutDate, String eipFile, String eipContentType, 
                                    String eipOperationType, String eipLangue, List<String> eipDescripition, Integer eipBuyoutTerm, Decimal eipRate, Date eipExpiryDate, 
                                    String sfdcCaseId, Decimal eipBalanceAmount, String eipActiveDirectoryName){ 
                                        
                                        //  eipLoginUser;  //Account_Verification.CustomAccountResponse ac, String error){
                
                this.eipSendEmail = eipSendEmail;
                this.eipCcSendEmail = eipCcSendEmail;
                this.eipAccount = eipAccount;
                this.eipContact = eipContact;
                this.eipContractNumber = eipContractNumber;
                this.eipCustId = eipCustId;
                this.eipTypeNote = eipTypeNote;
                this.eipAmount = eipAmount;
                this.eipEndOfTermFee = eipEndOfTermFee;
                this.eipTaxesGST = eipTaxesGST;
                this.eipTaxesPST = eipTaxesPST;
                this.eipTaxesHST = eipTaxesHST;
                this.eipTotalBuyout = eipTotalBuyout;
                this.eipBuyoutType = eipBuyoutType;
                this.eipFileName = eipFileName;
                this.eipBuyoutDate = eipBuyoutDate;
                this.eipFile = eipFile;
                this.eipContentType = eipContentType;
                this.eipOperationType = eipOperationType;
                this.eipRate = eipRate;
                this.eipBuyoutTerm = eipBuyoutTerm;
                this.eipDescripition = eipDescripition;
                this.eipLangue = eipLangue;
                this.eipExpiryDate = eipExpiryDate;
                this.sfdcCaseId = sfdcCaseId;
                this.eipBalanceAmount = eipBalanceAmount;
                this.eipActiveDirectoryName = eipActiveDirectoryName;
                                    }
*/}