public class SettingSendParam {
    
    public String SF_ParentHistoryId { get; set;}
    public String SF_HistoryId { get; set;}
    
    public String SendEmail { get; set;}
    public String CcSendEmail { get; set;}
    public String FromEmail { get; set;}
    public String EIP_Contact { get; set;}
    
    public String IL_Langue { get; set;}
    public String x_ActiveDirectoryName { get; set;}
    
    public String EIP_HistoricType { get; set;}
    public String EIP_EmailSubject { get; set;}
    public String EIP_EmailMessage { get; set;}
    
    

}