global class VendorRequest {
    
    
    global Integer MDMID;
    global StringValueRequest AccountEmailAddress;
    global StringValueRequest AccountManager;
    global StringValueRequest MainContact;
    global StringValueRequest TollFreePhone;
    global StringValueRequest Fax;
    global StringValueRequest Phone;
    global StringValueRequest WebsiteUrl;
    global StringValueRequest ShippingPostalCode;
    global StringValueRequest ShippingCountry;
    global StringValueRequest ShippingCountryCode;
    global StringValueRequest ShippingProvince;
    global StringValueRequest ShippingProvinceCode;
    global StringValueRequest ShippingCity;
    global StringValueRequest ShippingStreet;
    global StringValueRequest BillingPostalCode;
    global StringValueRequest BillingCountry;
    global StringValueRequest BillingCountryCode ;
    global StringValueRequest BillingProvince;
    global StringValueRequest BillingProvinceCode ;
    global StringValueRequest BillingCity;
    global StringValueRequest BillingStreet;
    global StringValueRequest BusinessName;
    global StringValueRequest LegalName;
    global SystemLocalRequest[] DestinationSystems;
    global SystemLocalRequest SourceSystem;
    global StringValueRequest YearEstablished;
    
    
    /*
    global Integer MDMID { get; set;}
    global String EmailAddress  { get; set;}
    global String BusinessName { get; set;}
    global StringVendorValue LegalName { get; set;} 
    global StringVendorValue BillingStreet { get; set;}
    global StringVendorValue BillingCity { get; set;}
    global StringVendorValue BillingProvince { get; set;}
    global StringVendorValue BillingCountry { get; set;}
    global StringVendorValue BillingPostalCode { get; set;}
    global StringVendorValue ShippingStreet { get; set;}
    global StringVendorValue ShippingCity { get; set;}
    global StringVendorValue ShippingProvince { get; set;}
    global StringVendorValue ShippingCountry { get; set;}
    global StringVendorValue ShippingPostalCode { get; set;}
    global StringVendorValue Phone { get; set;}    
    global StringVendorValue Fax { get; set;}
    global StringVendorValue TollFreePhone { get; set;}
    global StringVendorValue MainContact { get; set;}
    global StringVendorValue AccountManager { get; set;}
    global StringVendorValue SystemSource { get; set;}
    global StringVendorValue SystemId { get; set;}
    global StringVendorValue DestinationId { get; set;}
    */
    
    /*
    global Integer MDMID { get; set;}
    global String LegalName { get; set;} 
    global String BusinessName { get; set;}
    global String BillingStreet { get; set;}
    global String BillingCity { get; set;}
    global String BillingProvince { get; set;}
    global String BillingCountry { get; set;}
    global String BillingPostalCode { get; set;}
    global String ShippingStreet { get; set;}
    global String ShippingCity { get; set;}
    global String ShippingProvince { get; set;}
    global String ShippingCountry { get; set;}
    global String ShippingPostalCode { get; set;}
    global String Phone { get; set;}
    global String EmailAddress  { get; set;}
    global String Fax { get; set;}
    global String TollFreePhone { get; set;}
    global String MainContact { get; set;}
    global String AccountManager { get; set;}
    global String SystemSource { get; set;}
    global String SystemId { get; set;}
    global String DestinationId { get; set;}
*/
}